parameters:
    afm.site_status_checker.checker.doctrine.class: AFM\Bundle\SiteStatusCheckerBundle\Checker\Doctrine

services:
    afm.site_status_checker.checker.doctrine:
        class: %afm.site_status_checker.checker.doctrine.class%
        arguments: [@doctrine]