#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/bootstrap.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use AFM\Bundle\SiteStatusCheckerBundle\Tests\AppKernel;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

$kernel = new AppKernel("test", true);
$application = new Application($kernel);
$application->run($input);